spring:
  application:
    name: api-lol-champions-ai
  datasource:
    url: jdbc:h2:mem:champions_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true